# ============================================================
#  CONFIGURAZIONE DEL GIOCO — Cittadinanza Digitale
#
#  ISTRUZIONI PER LE IMMAGINI:
#  Salva le foto delle opere nella cartella  public/images/
#  con i nomi indicati nel campo "image" di ogni item.
#
#  Dimensioni consigliate: 800×800 px, formato JPG o PNG.
# ============================================================

CONFIG = {
    "title":    "Think Before You Click – Art for a Safer Internet",
    "subtitle": "Match each artwork to the correct category",

    "categories": [
        {
            "id":    "rispetto",
            "label": "Online Respect & Empathy",
            "color": "#27ae60",
            "icon":  "💚",
        },
        {
            "id":    "dipendenza",
            "label": "Digital Addiction",
            "color": "#9b59b6",
            "icon":  "📱",
        },
        {
            "id":    "cyberbullismo",
            "label": "Cyberbullying",
            "color": "#e74c3c",
            "icon":  "😡",
        },
        {
            "id":    "privacy",
            "label": "Privacy",
            "color": "#3498db",
            "icon":  "🔒",
        },
        {
            "id":    "fake-news",
            "label": "Fake News",
            "color": "#f39c12",
            "icon":  "📰",
        },
    ],

    # ── OPERE ──────────────────────────────────────────────────
    # Ogni item corrisponde a una delle opere fotografate.
    # "image" = nome del file in public/images/
    # "text"  = descrizione breve visibile sotto l'immagine
    # "correct" = id della categoria corretta
    # -----------------------------------------------------------
    "items": [
        {
            "id":      "opera-01",
            "name":    "Look at me, I'm real",
            "author":  "Chiara, Arianna",
            "image":   "/opera-01.jpeg",
            "text":    "Look at me, I'm real",
            "correct": "rispetto",
        },
        {
            "id":      "opera-02",
            "name":    "The Threads of Addiction",
            "author":  "Gill, Cristiana",
            "image":   "/opera-02.jpeg",
            "text":    "The Threads of Addiction",
            "correct": "dipendenza",
        },
        {
            "id":      "opera-03",
            "name":    "Words Can Hurt",
            "author":  "Gill, Cristiana, Alice, Serena",
            "image":   "/opera-03.jpg",
            "text":    "Words Can Hurt",
            "correct": "cyberbullismo",
        },
        {
            "id":      "opera-04",
            "name":    "Chaos on the Internet",
            "author":  "Francesco, Bejan",
            "image":   "/opera-04.jpeg",
            "text":    "Chaos on the Internet",
            "correct": "fake-news",
        },
        {
            "id":      "opera-05",
            "name":    "Think Before You Click",
            "author":  "Sofia, Simone",
            "image":   "/opera-05.jpeg",
            "text":    "Think Before You Click",
            "correct": "privacy",
        },
        {
            "id":      "opera-06",
            "name":    "The Sea That Does Not Give Back",
            "author":  "Giuseppe, Alessandro",
            "image":   "/opera-06.jpeg",
            "text":    "The Sea That Does Not Give Back",
            "correct": "privacy",
        },
        {
            "id":      "opera-07",
            "name":    "Towards Disconnection",
            "author":  "Erman, Giuseppe, Alessandro",
            "image":   "/opera-07.jpeg",
            "text":    "Towards Disconnection",
            "correct": "rispetto",
        },
        {
            "id":      "opera-08",
            "name":    "Holding Respect",
            "author":  "Sofia, Simone",
            "image":   "/opera-08.jpeg",
            "text":    "Holding Respect",
            "correct": "rispetto",
        },
        {
            "id":      "opera-09",
            "name":    "Digital Noise",
            "author":  "Marco, Nocolò",
            "image":   "/IMG_3018.jpeg",
            "text":    "Digital Noise",
            "correct": "dipendenza",
        },
        {
            "id":      "3072",
            "name":    "Target",
            "author":  "Fabio, Leonardo",
            "image":   "/IMG_3072.jpeg",
            "text":    "Target",
            "correct": "cyberbullismo",
        },
         {
            "id":      "3074",
            "name":    "Words Do Evil",
            "author":  "Gabriele, Keyla",
            "image":   "/IMG_3074.jpeg",
            "text":    "Words Do Evil",
            "correct": "cyberbullismo",
        },
         {
            "id":      "3027",
            "name":    "Digital Bait",
            "author":  "Gabriele, Keyla, Nicole",
            "image":   "/IMG_3027.jpeg",
            "text":    "Digital Bait",
            "correct": "fake-news",
        },
         {
            "id":      "3020",
            "name":    "The thread of judgment",
            "author":  "Leonardo, Alessia, Daniel",
            "image":   "/IMG_3020.jpeg",
            "text":    "The thread of judgment",
            "correct": "rispetto",
        },
         {
            "id":      "3067",
            "name":    "Kindness Remains",
            "author":  "Alessia, Mattia",
            "image":   "/IMG_3067.jpeg",
            "text":    "Kindness Remains",
            "correct": "rispetto",
        },
         {
            "id":      "3021",
            "name":    "Digital Loniless",
            "author":  "Edoardo, Ferdinando, Fabio",
            "image":   "/IMG_3021.jpeg",
            "text":    "Digital Loniless",
            "correct": "cyberbullismo",
        },
         {
            "id":      "3065",
            "name":    "Digital waves",
            "author":  "Emma, Valentina, Paola",
            "image":   "/IMG_3065.jpeg",
            "text":    "Digital waves",
            "correct": "dipendenza",
        },
         {
            "id":      "3073",
            "name":    "Block hate",
            "author":  "Emma, Valentina, Paola",
            "image":   "/IMG_3073.jpeg",
            "text":    "Block hate",
            "correct": "cyberbullismo",
        },
         {
            "id":      "3069",
            "name":    "Fragments of Identity",
            "author":  "Nicole",
            "image":   "/IMG_3069.jpeg",
            "text":    "Fragments of Identity",
            "correct": "privacy",
        },
        {
            "id":      "1000102754",
            "name":    "",
            "author":  "",
            "image":   "/1000102754.jpg",
            "text":    "",
            "correct": "",
        },
         {
            "id":      "1000102756",
            "name":    "",
            "author":  "",
            "image":   "/1000102756.jpg",
            "text":    "",
            "correct": "",
        },
         {
            "id":      "1000103387",
            "name":    "",
            "author":  "",
            "image":   "/1000103387.jpg",
            "text":    "",
            "correct": "",
        },
         {
            "id":      "1000103388",
            "name":    "",
            "author":  "",
            "image":   "/1000103388.jpg",
            "text":    "",
            "correct": "",
        },
         {
            "id":      "1000103389",
            "name":    "",
            "author":  "",
            "image":   "/1000103389.jpg",
            "text":    "",
            "correct": "",
        },
         {
            "id":      "1000103390",
            "name":    "",
            "author":  "",
            "image":   "/1000103390.jpg",
            "text":    "",
            "correct": "",
        },
         {
            "id":      "1000103391",
            "name":    "",
            "author":  "",
            "image":   "/1000103391.jpg",
            "text":    "",
            "correct": "",
        },
         {
            "id":      "1000103392",
            "name":    "",
            "author":  "",
            "image":   "/1000103392.jpg",
            "text":    "",
            "correct": "",
        },
         {
            "id":      "1000103393",
            "name":    "",
            "author":  "",
            "image":   "/1000103393.jpg",
            "text":    "",
            "correct": "",
        },
         {
            "id":      "1000103394",
            "name":    "",
            "author":  "",
            "image":   "/1000103394.jpg",
            "text":    "",
            "correct": "",
        },
         {
            "id":      "1000103395",
            "name":    "",
            "author":  "",
            "image":   "/1000103395.jpg",
            "text":    "",
            "correct": "",
        },
         {
            "id":      "1000103396",
            "name":    "",
            "author":  "",
            "image":   "/1000103396.jpg",
            "text":    "",
            "correct": "",
        },
         {
            "id":      "1000103397",
            "name":    "",
            "author":  "",
            "image":   "/1000103397.jpg",
            "text":    "",
            "correct": "",
        },
         {
            "id":      "1000103398",
            "name":    "",
            "author":  "",
            "image":   "/1000103398.jpg",
            "text":    "",
            "correct": "",
        },
    ],
}
